### ISSUE TITLE
Upgrade basemap server to NGINX 1.26

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ose-basemap-server#3]
NGINX 1.24 [reached EoL in April 2024](https://endoflife.date/nginx). As such, we need to upgrade the version of NGINX running on DO droplet basemap-server-22-lts to 1.26

## Acceptance Criteria
- [ ] NGINX docker image on basemap-server-22-lts is upgraded to 1.26

**Comment by TylerMatteo** [comment]
@TangoYankee let me know when you've worked out a plan for this, then we can talk timeline for execution.

**Comment by TangoYankee** [comment]
The plan is to 

1) Integrate #4 onto main
2) Pull the updated code onto the droplet
3) Run `docker compose up --build` on the droplet images
4) Update the nginx cert while we're in there

Zero downtime expected- the existing build will run until the 1.26.1 build spins up.
